/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gmail.itsango.log4j2.sample;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class App {

    static final Logger logger = LogManager.getFormatterLogger();

    public static void main(String[] args) throws InterruptedException {
        System.getProperties().forEach((k, v)->logger.info("%s=%s", k, v));
        for (;;) {
            logger.trace("trace");
            logger.info("info");
            logger.warn("warn");
            logger.error("error");
            logger.fatal("fatal");
            Thread.sleep(1000);
        }
    }
}
